language: generic

script:
  - make
  - make test

sudo: false

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: clang3.9
      env:
        - CC=clang-3.9
        - CXX=clang++-3.9
        - NINJA_JOBS=2 # Travis is so parallel it runs out of memory. Limit that.
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-3.9
            - pkg-config
            - zlib1g-dev
            - libpng-dev
            - libxml2-dev
            - ninja-build
            - cmake
            - cmake-data
    - os: linux
      dist: trusty
      compiler: gcc4.8
      env:
        - CC=gcc-4.8
        - CXX=g++-4.8
        - NINJA_JOBS=2 # Travis is so parallel it runs out of memory. Limit that.
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.8
            - g++-4.8
            - pkg-config
            - zlib1g-dev
            - libpng-dev
            - libxml2-dev
            - ninja-build
            - cmake
            - cmake-data
    - os: osx
      osx_image: xcode7.2
      compiler: clang
      before_install:
        - brew update
      install:
        - brew reinstall cmake
        - brew reinstall ninja
